import { AntDesign } from "@expo/vector-icons";
import { Pitcher, Subscription } from "@probable/db";
import { PermissionStatus } from "expo-modules-core";
import * as Notifications from "expo-notifications";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, StyleProp, View, ViewStyle } from "react-native";
import Animated, {
  Easing,
  FadeIn,
  FadeInLeft,
  FadeOut,
  FadeOutLeft,
  Layout,
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from "react-native-reanimated";
import * as Sentry from "sentry-expo";
import ButtonContainer from "../components/ButtonContainer";
import SearchInput from "../components/SearchInput";
import {
  AlertText,
  PrimaryText,
  SecondaryText,
  SpecialText,
  specialTextColor,
  ThemedView,
} from "../components/Themed";
import { trpc } from "../components/TRPCProvider";
import { useTrackParallelMutations } from "@probable/common";
import tw from "../tailwind";
import ModalLayout from "../components/ModalLayout";
import { ClassInput } from "twrnc/dist/esm/types";
import HeaderRightContainer from "../components/HeaderRightContainer";

type PitcherSubscription =
  Pitcher & {
    subscription?: Subscription
  };

export const Subscriptions = () => {
  const mutationTracker = useTrackParallelMutations();

  const {
    data: subscriptions,
    isSuccess: subscriptionsFetched,
    isFetching: subscriptionsFetching,
    isError: isSubscriptionsError,
    error: subscriptionsError
  } = trpc.subscription.byUserId.useQuery(undefined, {
    enabled: !mutationTracker.isMutating(),
    refetchOnMount: false,
  });

  if (isSubscriptionsError) {
    Sentry.Native.captureException(
      `Error fetching subscriptions on homepage: ${subscriptionsError}`
    );
  }

  const [searchFilter, setSearchFilter] = useState<string>();
  const [isSearchActive, setIsSearchActive] = useState<boolean>(false);

  const {
    data: pitchersFromSearch,
    isSuccess,
    isInitialLoading,
    isFetching,
    isError: isSearchError,
    error: searchError
  } = trpc.pitcher.byFuzzyName.useQuery(searchFilter!, {
    enabled: !!searchFilter && subscriptionsFetched,
  });

  if (isSearchError) {
    Sentry.Native.captureException(
      `Error fuzzy searching for pitchers on homepage: ${searchError}`
    );
  }

  const utils = trpc.useContext();

  const pitchers = pitchersFromSearch?.map((pitcher) => ({
    ...pitcher,
    subscription:
      subscriptions?.find((sub) => sub.pitcherId === pitcher.id) || undefined,
  }));

  const { mutate: subscribe } = trpc.subscription.create.useMutation({
    onMutate: ({ pitcherId }) => {
      mutationTracker.startOne();
      const previousSubscriptions = utils.subscription.byUserId.getData();
      utils.subscription.byUserId.setData(undefined, (old) => {
        if (old) {
          const pitcher = pitchers?.find((p) => p.id === pitcherId);
          if (pitcher) {
            return [
              ...old,
              // Optimistically add a new subscription with some dummy data.
              // This dummy data will be replaced with ids generated by the
              // database once the mutation completes.
              {
                id: new Date().valueOf(),
                enabled: true,
                pitcherId: pitcherId,
                userId: "loading",
                pitcher: {
                  id: pitcherId,
                  name: pitcher.name,
                  teamId: pitcher.teamId,
                  homeGames: pitcher.subscription?.pitcher.homeGames || [],
                  awayGames: pitcher.subscription?.pitcher.awayGames || [],
                },
              },
            ];
          }
        }
      });
      return { previousSubscriptions };
    },
    onError: (err, newSubscription, context) => {
      utils.subscription.byUserId.setData(undefined, context?.previousSubscriptions);
      Sentry.Native.captureException(err);
    },
    onSettled: () => {
      mutationTracker.endOne();
      if (mutationTracker.allEnded()) {
        utils.subscription.byUserId.invalidate();
        utils.pitcher.byNameSearch.invalidate();
      }
    },
  });

  const { mutate: unsubscribe } = trpc.subscription.delete.useMutation({
    onMutate: (subscriptionId) => {
      mutationTracker.startOne();
      const previousSubscriptions = utils.subscription.byUserId.getData();
      utils.subscription.byUserId.setData(undefined, (old) =>
        old?.filter((s) => s.id !== subscriptionId)
      );
      return { previousSubscriptions };
    },
    onError: (err, newSubscription, context) => {
      utils.subscription.byUserId.setData(undefined, context?.previousSubscriptions);
      Sentry.Native.captureException(err);
    },
    onSettled: () => {
      mutationTracker.endOne();
      if (mutationTracker.allEnded()) {
        utils.subscription.byUserId.invalidate();
        utils.pitcher.byNameSearch.invalidate();
      }
    },
  });

  // Why not just use section list? It doesn't have support from Reanimated's "itemLayoutAnimation"
  // prop, which we are depending on below for the cool layout transitions.
  const subscribedAndAvailablePitchers: (
    | string
    | PitcherSubscription
  )[] = [];

  if (subscriptions) {
    const subscribedPitchers =
      (searchFilter
        ? pitchers
          ?.filter((p) => p.subscription)
          .map(
            (p) =>
            ({
              id: p.id,
              name: p.name,
              teamId: p.teamId,
              subscription: {
                id: p.subscription!.id,
                pitcherId: p.id,
                userId: p.subscription!.userId,
              },
            } as PitcherSubscription)
          )
        : subscriptions.map(
          (s) =>
          ({
            id: s.pitcher.id,
            name: s.pitcher.name,
            teamId: s.pitcher.teamId,
            subscription: {
              id: s.id,
              pitcherId: s.pitcherId,
              userId: s.userId,
            },
          } as PitcherSubscription)
        )) || [];
    if (!!subscribedPitchers.length) {
      subscribedAndAvailablePitchers.push("Subscribed");
      subscribedAndAvailablePitchers.push(...subscribedPitchers);
    }
  }

  if (searchFilter) {
    const availablePitchers =
      pitchers?.filter((p) => !p.subscription) || [] || [];
    if (!!availablePitchers.length) {
      subscribedAndAvailablePitchers.push("Available");
      subscribedAndAvailablePitchers.push(...availablePitchers);
    }
  }
  const pauseMutations =
    mutationTracker.isMutating() ||
    isFetching ||
    (!isSuccess && !!searchFilter) ||
    subscriptionsFetching;
  const opacity = useSharedValue(1);

  useEffect(() => {
    opacity.value = withTiming(pauseMutations ? 0.4 : 1, {
      duration: 150,
      easing: Easing.linear,
    });
  }, [pauseMutations]);

  const style = useAnimatedStyle(() => ({ opacity: opacity.value }), []);

  const [isEditing, setIsEditing] = useState(false);

  useEffect(() => {
    if (isSearchActive) setIsEditing(false);
  }, [isSearchActive]);

  return (
    <ModalLayout>
      <HeaderRightContainer>
        <ButtonContainer onPress={() => setIsEditing((isEditing) => !isEditing)}>
          {isEditing ? (
            <SpecialText style={tw`font-bold`}>
              Done
            </SpecialText>
          ) : (
            <SpecialText>
              Edit
            </SpecialText>
          )}
        </ButtonContainer>
      </HeaderRightContainer>
      <Animated.View style={tw`pt-6 px-4 flex-1`} layout={Layout.duration(1)}>
        <SearchInput
          onChange={(text) => setSearchFilter(text)}
          onActive={() => setIsSearchActive(true)}
          onCancel={() => setIsSearchActive(false)}
        />
        <Animated.FlatList
          // @ts-ignore - there is a type bug in Reanimated 2.9.x
          itemLayoutAnimation={Layout.duration(250)}
          bounces={isSearchActive}
          keyExtractor={(item) => {
            if (typeof item === "string") {
              return item;
            }
            return String(item.id);
          }}
          contentContainerStyle={tw`pb-12`}
          data={subscribedAndAvailablePitchers}
          keyboardShouldPersistTaps="handled"
          renderItem={({ index, item }) => {
            if (typeof item === "string") {
              return (
                <Animated.View entering={FadeIn} exiting={FadeOut}>
                  <View style={tw`flex-row justify-between mb-1 mx-4`}>
                    <SecondaryText style={tw`uppercase text-sm`}>
                      {item}
                    </SecondaryText>
                    {index === 0 &&
                      (isFetching ||
                        (!isSuccess && !!searchFilter) ||
                        mutationTracker.isMutating() ||
                        subscriptionsFetching) && (
                        <Animated.View entering={FadeIn} exiting={FadeOut}>
                          <ActivityIndicator size="small" />
                        </Animated.View>
                      )}
                  </View>
                </Animated.View>
              );
            } else {
              return (
                <Animated.View entering={FadeIn} exiting={FadeOut}>
                  <PitcherSubscription
                    subscribeHandler={async () => {
                      subscribe({
                        pitcherId: item.id,
                      });
                    }}
                    unsubscribeHandler={isEditing && !isSearchActive ? () => {
                      unsubscribe(item.subscription!.id);
                    } : undefined}
                    pitcher={item}
                    subscription={item.subscription}
                    disabled={pauseMutations}
                    style={tw.style(
                      "border-b-2",
                      typeof subscribedAndAvailablePitchers[index - 1] ===
                        "string"
                        ? "rounded-t-xl"
                        : undefined,
                      !subscribedAndAvailablePitchers[index + 1] ||
                        typeof subscribedAndAvailablePitchers[index + 1] ===
                        "string"
                        ? "border-b-0 rounded-b-xl mb-3"
                        : undefined
                    )}
                    buttonStyle={style}
                  />
                </Animated.View>
              );
            }
          }}
          ListEmptyComponent={
            <>
              {isSuccess && (
                <Animated.View entering={FadeIn.delay(150)} exiting={FadeOut}>
                  <SecondaryText
                    style={tw`mb-6 mx-4 text-sm`}
                    accessibilityRole="summary"
                  >
                    No pitchers found. Try changing your search.
                  </SecondaryText>
                </Animated.View>
              )}
              {isInitialLoading ? (
                <Animated.View
                  style={tw`pt-6`}
                  entering={FadeIn}
                  exiting={FadeOut}
                >
                  <ActivityIndicator
                    size="large"
                    color={String(tw.style(specialTextColor).color)}
                  />
                </Animated.View>
              ) : (
                !isSuccess && (
                  <Animated.View entering={FadeIn} exiting={FadeOut}>
                    <SecondaryText
                      style={tw`mb-6 mx-4 text-sm`}
                      accessibilityRole="summary"
                    >
                      Search for your favorite pitcher to add them to your list of subscriptions.
                    </SecondaryText>
                  </Animated.View>
                )
              )}
              {isSearchError && (
                <Animated.View entering={FadeIn.delay(150)} exiting={FadeOut}>
                  <AlertText
                    style={tw`mb-6 mx-4 text-sm`}
                    accessibilityRole="alert"
                  >
                    An error occurred while performing your search. Please try
                    again later.
                  </AlertText>
                </Animated.View>
              )}
            </>
          }
        />
      </Animated.View>
    </ModalLayout >
  );
};

const PitcherSubscription = ({
  subscribeHandler,
  unsubscribeHandler,
  pitcher,
  subscription,
  disabled,
  style,
  buttonStyle
}: {
  subscribeHandler: () => void;
  unsubscribeHandler?: () => void;
  pitcher: Pitcher;
  subscription?: Subscription;
  disabled?: boolean;
  style?: ClassInput;
  buttonStyle: StyleProp<Animated.AnimateStyle<StyleProp<ViewStyle>>>;
}) => {
  return (
    <>
      <ThemedView
        style={tw.style(style)}
      >
        {subscription && unsubscribeHandler && (
          <Animated.View entering={FadeInLeft} exiting={FadeOutLeft}>
            <ButtonContainer
              style={tw`-my-3 -ml-4 p-3`}
              onPress={unsubscribeHandler}
              accessibilityLabel={""}
              disabled={disabled}
            >
              <Animated.View style={buttonStyle}>
                <AlertText>
                  <AntDesign name="minuscircle" size={20} />
                </AlertText>
              </Animated.View>
            </ButtonContainer>
          </Animated.View>
        )}
        {!subscription && (
          <ButtonContainer
            style={tw`-my-3 -ml-4 p-3`}
            onPress={subscribeHandler}
            accessibilityLabel={""}
            disabled={disabled}
          >
            <Animated.View style={buttonStyle}>
              <SpecialText>
                <AntDesign name="pluscircle" size={20} />
              </SpecialText>
            </Animated.View>
          </ButtonContainer>
        )}
        <Animated.View style={tw`flex-1 pr-9.5`} layout={Layout}>
          <PrimaryText numberOfLines={1}>
            {pitcher.name}
          </PrimaryText>
        </Animated.View>
      </ThemedView>
    </>
  );
};
