import { AntDesign } from "@expo/vector-icons";
import { Pitcher, Subscription } from "@prisma/client";
import { PermissionStatus } from "expo-modules-core";
import * as Notifications from "expo-notifications";
import React, { useState } from "react";
import { ActivityIndicator, SectionList } from "react-native";
import Animated, { FadeIn, FadeOut, Layout } from "react-native-reanimated";
import * as Sentry from "sentry-expo";
import ButtonContainer from "../components/ButtonContainer";
import ScreenLayout from "../components/ScreenLayout";
import SearchInput from "../components/SearchInput";
import {
  AlertText,
  PrimaryText,
  SecondaryText,
  SpecialText,
  specialTextColor,
  ThemedView,
} from "../components/Themed";
import { trpc } from "../components/TRPCProvider";
import { useTrackParallelMutations } from "../hooks/use-track-parallel-mutations";
import tw from "../tailwind";

export const Subscribe = () => {
  const { data: subscriptions, isSuccess: subscriptionsFetched } =
    trpc.subscription.byUserId.useQuery();

  const [searchFilter, setSearchFilter] = useState<string>();

  const {
    data: pitchersFromSearch,
    isSuccess,
    isInitialLoading,
    isError,
  } = trpc.pitcher.byNameSearch.useQuery(searchFilter?.split(" ") || [], {
    enabled: !!searchFilter && subscriptionsFetched,
  });

  const utils = trpc.useContext();

  const pitchers = pitchersFromSearch?.map((pitcher) => ({
    ...pitcher,
    subscription:
      subscriptions?.find((sub) => sub.pitcherId === pitcher.id) || undefined,
  }));

  const mutationTracker = useTrackParallelMutations();

  const { mutate: subscribe } = trpc.subscription.create.useMutation({
    onMutate: ({ pitcherId }) => {
      mutationTracker.startOne();
      const previousSubscriptions = utils.subscription.byUserId.getData();
      utils.subscription.byUserId.setData((old) => {
        if (old) {
          const pitcher = pitchers?.find((p) => p.id === pitcherId);
          if (pitcher) {
            return [
              ...old,
              // Optimistically add a new subscription with some dummy data.
              // This dummy data will be replaced with ids generated by the
              // database once the mutation completes.
              {
                id: new Date().valueOf(),
                enabled: true,
                pitcherId: pitcherId,
                userId: "loading",
                pitcher: {
                  id: pitcherId,
                  name: pitcher.name,
                  teamId: pitcher.teamId,
                  homeGames: pitcher.subscription?.pitcher.homeGames || [],
                  awayGames: pitcher.subscription?.pitcher.awayGames || [],
                },
              },
            ];
          }
        }
      });
      return { previousSubscriptions };
    },
    onError: (err, newSubscription, context) => {
      utils.subscription.byUserId.setData(context?.previousSubscriptions);
      Sentry.Native.captureException(err);
    },
    onSettled: () => {
      mutationTracker.endOne();
      if (mutationTracker.allEnded()) {
        utils.subscription.byUserId.invalidate();
        utils.pitcher.byNameSearch.invalidate();
      }
    },
  });

  const { mutate: unsubscribe } = trpc.subscription.delete.useMutation({
    onMutate: (subscriptionId) => {
      mutationTracker.startOne();
      const previousSubscriptions = utils.subscription.byUserId.getData();
      utils.subscription.byUserId.setData((old) =>
        old?.map((s) =>
          s.id !== subscriptionId ? s : { ...s, userId: "loading" }
        )
      );
      return { previousSubscriptions };
    },
    onError: (err, newSubscription, context) => {
      utils.subscription.byUserId.setData(context?.previousSubscriptions);
      Sentry.Native.captureException(err);
    },
    onSettled: () => {
      mutationTracker.endOne();
      if (mutationTracker.allEnded()) {
        utils.subscription.byUserId.invalidate();
        utils.pitcher.byNameSearch.invalidate();
      }
    },
  });

  const [pushStatus, setPushStatus] = useState<PermissionStatus>();

  Notifications.getPermissionsAsync().then(({ status }) => {
    setPushStatus(status);
  });

  const subscribedAndAvailablePitchers: {
    title: string;
    data: (Pitcher & { subscription?: Subscription })[];
  }[] = [];

  if (subscriptions) {
    subscribedAndAvailablePitchers.push({
      title: "Subscribed",
      data:
        (searchFilter
          ? pitchers
              ?.filter((p) => p.subscription)
              .map(
                (p) =>
                  ({
                    id: p.id,
                    name: p.name,
                    teamId: p.teamId,
                    subscription: {
                      id: p.subscription!.id,
                      pitcherId: p.id,
                      userId: p.subscription!.userId,
                    },
                  } as Pitcher & { subscription?: Subscription })
              )
          : subscriptions.map(
              (s) =>
                ({
                  id: s.pitcher.id,
                  name: s.pitcher.name,
                  teamId: s.pitcher.teamId,
                  subscription: {
                    id: s.id,
                    pitcherId: s.pitcherId,
                    userId: s.userId,
                  },
                } as Pitcher & { subscription?: Subscription })
            )) || [],
    });
  }

  if (searchFilter) {
    subscribedAndAvailablePitchers.push({
      title: "Available",
      data: pitchers?.filter((p) => !p.subscription) || [],
    });
  }

  return (
    <ScreenLayout>
      <SectionList
        contentContainerStyle={tw`px-3 pt-9 pb-12`}
        sections={subscribedAndAvailablePitchers}
        keyboardShouldPersistTaps="handled"
        renderSectionHeader={({ section: { title, data } }) => (
          <>
            {data && data.length > 0 && (
              <Animated.View
                entering={FadeIn}
                exiting={FadeOut}
                layout={Layout}
              >
                <SecondaryText style={tw`ml-3 mb-1.5 uppercase text-sm`}>
                  {title}
                </SecondaryText>
              </Animated.View>
            )}
            {!data ||
              (data.length === 0 && title === "Available" && isInitialLoading && (
                <Animated.View entering={FadeIn} exiting={FadeOut}>
                  <ActivityIndicator
                    size="large"
                    color={String(tw.style(specialTextColor).color)}
                  />
                </Animated.View>
              ))}
          </>
        )}
        renderItem={({ index, item, section }) => (
          <Animated.View entering={FadeIn.delay(200)} exiting={FadeOut}>
            <ThemedView
              style={tw.style(
                "border-b-2",
                index === 0 ? "rounded-t-xl" : undefined,
                index + 1 === section.data.length
                  ? "border-b-0 rounded-b-xl mb-6"
                  : undefined
              )}
            >
              <PrimaryText style={tw`flex-1 pr-2.5`} numberOfLines={1}>
                {item.name}
              </PrimaryText>
              {item.subscription && item.subscription.userId === "loading" && (
                <ActivityIndicator size="small" />
              )}
              {item.subscription && item.subscription.userId !== "loading" && (
                <ButtonContainer
                  style={tw`absolute right-0 py-4 pl-4 pr-3`}
                  onPress={() => {
                    unsubscribe(item.subscription!.id);
                  }}
                  disabled={mutationTracker.isMutating()}
                  accessibilityLabel={""}
                >
                  <AlertText>
                    <AntDesign name="minuscircle" size={20} />
                  </AlertText>
                </ButtonContainer>
              )}
              {!item.subscription && (
                <ButtonContainer
                  style={tw`absolute right-0 py-4 pl-4 pr-3`}
                  onPress={async () => {
                    if (pushStatus === PermissionStatus.DENIED) {
                      alert(
                        "Permission for this application to send push notifications has been denied. To receive alerts, you must allow notifications for Probable Pitcher in your phone's application settings."
                      );
                    }
                    subscribe({
                      pitcherId: item.id,
                    });
                  }}
                  disabled={mutationTracker.isMutating()}
                >
                  <SpecialText>
                    <AntDesign name="pluscircle" size={20} />
                  </SpecialText>
                </ButtonContainer>
              )}
            </ThemedView>
          </Animated.View>
        )}
        ListHeaderComponent={
          <SearchInput
            onChange={(text) => {
              setSearchFilter(text);
            }}
          />
        }
        ListEmptyComponent={
          <>
            {isSuccess && (
              <Animated.View entering={FadeIn.delay(150)} exiting={FadeOut}>
                <SecondaryText
                  style={tw`mb-9 mx-3 text-sm`}
                  accessibilityRole="summary"
                >
                  No pitchers found. Try changing your search.
                </SecondaryText>
              </Animated.View>
            )}
            {isInitialLoading ? (
              <Animated.View entering={FadeIn} exiting={FadeOut}>
                <ActivityIndicator
                  size="large"
                  color={String(tw.style(specialTextColor).color)}
                />
              </Animated.View>
            ) : (
              !isSuccess && (
                <Animated.View entering={FadeIn} exiting={FadeOut}>
                  <SecondaryText
                    style={tw`mb-9 mx-3 text-sm`}
                    accessibilityRole="summary"
                  >
                    Enter a players name to perform a search.
                  </SecondaryText>
                </Animated.View>
              )
            )}
            {isError && (
              <Animated.View entering={FadeIn.delay(150)} exiting={FadeOut}>
                <AlertText
                  style={tw`mb-9 mx-3 text-sm`}
                  accessibilityRole="alert"
                >
                  An error occurred while performing your search. Please try
                  again later.
                </AlertText>
              </Animated.View>
            )}
          </>
        }
      />
    </ScreenLayout>
  );
};
