name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: Build and publish nextjs image
        run: |
          docker build . --file apps/nextjs/Dockerfile --tag ghcr.io/tmlamb/probable-pitchers-nextjs:latest --tag ghcr.io/tmlamb/probable-pitchers-nextjs:${{ github.sha }}
          docker push --all-tags ghcr.io/tmlamb/probable-pitchers-nextjs
      - name: Build and publish ingest image
        run: |
          docker build . --file apps/ingest/Dockerfile --tag ghcr.io/tmlamb/probable-pitchers-ingest:latest --tag ghcr.io/tmlamb/probable-pitchers-ingest:${{ github.sha }}
          docker push --all-tags ghcr.io/tmlamb/probable-pitchers-ingest
