name: Prod Release
on:
  release:
    types: [published]

jobs:
  tag-images:
    name: Tag Container Images
    runs-on: ubuntu-latest
    steps:
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: Tag nextjs image with version
        run: |
          docker pull ghcr.io/tmlamb/probable-pitchers-nextjs:latest
          docker tag ghcr.io/tmlamb/probable-pitchers-nextjs:latest ghcr.io/tmlamb/probable-pitchers-nextjs:${{ github.ref_name }}
          docker push ghcr.io/tmlamb/probable-pitchers-nextjs:${{ github.ref_name }}
      - name: Tag ingest image with version
        run: |
          docker pull ghcr.io/tmlamb/probable-pitchers-ingest:latest
          docker tag ghcr.io/tmlamb/probable-pitchers-ingest:latest ghcr.io/tmlamb/probable-pitchers-ingest:${{ github.ref_name }}
          docker push ghcr.io/tmlamb/probable-pitchers-ingest:${{ github.ref_name }}
  deploy-infra:
    name: Update Infrastructure
    needs: tag-images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_PROD }}"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
      - id: "get-credentials"
        uses: "google-github-actions/get-gke-credentials@v0"
        with:
          cluster_name: "probable-pitchers"
          location: "us-central1"
      - run: cd infrastructure && npm install
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: prod
          work-dir: infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DEPLOY_COMMIT_TAG: ${{ github.ref_name }}
  update-production:
    name: Update Production App
    needs: deploy-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run semver-diff
        id: semver-diff
        uses: tj-actions/semver-diff@v2.1.0
      - name: Show release type
        run: |
          echo "Release type: ${{ steps.semver-diff.outputs.release_type }}"
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Publish Update
        if: ${{ steps.semver-diff.outputs.release_type != 'major' }}
        run: cd apps/expo && APP_ENV=production API_BASE_URL="https://probablepitchers.net" NEXTAUTH_URL="https://probablepitchers.net" SENTRY_PUBLIC_DSN="${{ secrets.SENTRY_PUBLIC_DSN }}"" eas update --branch production --message "${{ github.event.release.name }}"
      - name: App Store Build
        if: ${{ steps.semver-diff.outputs.release_type == 'major' }}
        run: cd apps/expo && eas build --profile production --platform all
