name: Prod Release
on:
  release:
    types: [published]

jobs:
  tag-images:
    name: Tag Container Images
    runs-on: ubuntu-latest

    steps:
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Tag nextjs image for release version
        run: |
          docker pull ghcr.io/tmlamb/probable-pitchers-nextjs:latest
          docker tag ghcr.io/tmlamb/probable-pitchers-nextjs:latest ghcr.io/tmlamb/probable-pitchers-nextjs:${{ github.ref_name }}
          docker push ghcr.io/tmlamb/probable-pitchers-nextjs:${{ github.ref_name }}

      - name: Tag ingest image for release version
        run: |
          docker pull ghcr.io/tmlamb/probable-pitchers-ingest:latest
          docker tag ghcr.io/tmlamb/probable-pitchers-ingest:latest ghcr.io/tmlamb/probable-pitchers-ingest:${{ github.ref_name }}
          docker push ghcr.io/tmlamb/probable-pitchers-ingest:${{ github.ref_name }}

  deploy-infra:
    name: Update Infrastructure
    needs: tag-images
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_PROD }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Get GKR Credentials"
        uses: "google-github-actions/get-gke-credentials@v1"
        with:
          cluster_name: "probable-pitchers"
          location: "us-central1"

      - name: "Install dependencies"
        run: cd infrastructure && npm ci

      - name: "Update production stack"
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: prod
          work-dir: infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          DEPLOY_COMMIT_TAG: ${{ github.ref_name }}
          CHANGED_INGEST: true
          CHANGED_NEXTJS: true

  update-production:
    name: Update Production App
    needs: deploy-infra
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run semver-diff
        id: semver-diff
        uses: tj-actions/semver-diff@v2.1.0

      - name: Show release type
        run: |
          echo "Release type: ${{ steps.semver-diff.outputs.release_type }}"

      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Publish Live Update
        if: ${{ steps.semver-diff.outputs.release_type == 'patch' }}
        run: cd apps/expo && APP_ENV=production NEXTAUTH_URL="https://probablepitcher.com" SENTRY_PUBLIC_DSN="${{ secrets.SENTRY_PUBLIC_DSN }}" eas update --branch production --message "${{ github.event.release.name }}"

      - name: App Store Build
        if: ${{ steps.semver-diff.outputs.release_type == 'major' || steps.semver-diff.outputs.release_type == 'minor' }}
        run: cd apps/expo && eas build --profile production --platform all --non-interactive
