name: Scan Images

jobs:
  tag-images:
    name: Tag Container Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: Scan ingest image
        uses: anchore/scan-action@v3
        with:
          image: "ghcr.io/tmlamb/probable-pitchers-nextjs:latest"
      - name: Scan nextjx image
        uses: anchore/scan-action@v3
        with:
          image: "ghcr.io/tmlamb/probable-pitchers-ingest:latest"
